# hms/Dockerfile
FROM php:8.2-apache

# Install extensions commonly needed for PHP+MySQL projects
RUN apt-get update && apt-get install -y \
    libpng-dev libjpeg-dev libfreetype6-dev zip unzip \
  && docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-install mysqli pdo pdo_mysql gd \
  && rm -rf /var/lib/apt/lists/*

# Enable Apache mod_rewrite (important for PHP routing)
RUN a2enmod rewrite

# Copy all backend PHP files into Apache web root
COPY . /var/www/html/


RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html

# Expose port 80 (default Apache port)
EXPOSE 80
